#!/bin/bash

export TUFIN_PS_HOME=/opt/tufin/securitysuite/ps
[[ :$PATH: == *:/usr/local/bin:* ]] || export PATH=/usr/local/bin:"$PATH"
[[ :$PATH: == *:/opt/local/bin:* ]] || export PATH=/opt/local/bin:"$PATH"
[[ :$PATH: == *:"$TUFIN_PS_HOME"/bin:* ]] || export PATH="$TUFIN_PS_HOME"/bin:"$PATH"
[[ :$PATH: == *:"$TUFIN_PS_HOME"/python/bin:* ]] || export PATH="$TUFIN_PS_HOME"/python/bin:"$PATH"

exec -a asash /opt/local/bin/asamock.py "$@"
