#!/bin/bash

scriptname=ifconfig-loopbacks
version=0.1

ifname=lo0
UNAME=$(uname) || exit
if [ "$UNAME" == "Darwin" ]; then ifname=lo0;
elif [ "$UNAME" == "Linux" ]; then ifname=lo;
else
	echo "Error: the $UNAME platform is not supported." >&2
	exit 1
fi
if [ "$1" == "--help" ]; then
	cat <<EOF
Usage: $0 [OPTION]...
Configure the loopback interface with a large number of alias addresses.

-alias, --no-alias, -d	remove the aliases instead of adding them
--interface=if, -i if	use the interface \`if' instead of the default
			interface \`$ifname'
-f, --force		adds the aliases back even if they seem to already
			exist
--subnet=a.b.2.0[/23]	uses the subnet a.b.2.0/23 instead of 127.200.2/23;
			pattern will be a.b.0.2 - a.b.0.254 for a total of
			500 addresses
--ncsubnet=a.b.0.1[/21]	uses the pattern a.b.0.1, a.b.0.5, etc.; will be a
			total of 512 addresses
-n, --dry-run		show the commands that would be executed instead of
			actually executing them
-l, --list		only list out IP addresses, do nothing else
--hostprefix=PREFIX	alter /etc/hosts, use given PREFIX like \`site'
--hostfile=HOSTFILE	use HOSTFILE instead of /etc/hosts
    --help		display this help and exit
    --version		output version information ($version) and exit

The addresses assigned will be in the subnet 127.200.2.0/23 and will range
from 127.200.2.2 - 127.200.2.251 and 127.200.3.2 - 127.200.3.251, for a
total of 500 addresses. You will need to run as a user which has permission to
run the \`ifconfig' command against the selected interface.
EOF
	exit 0
elif [ "$1" == "--version" ]; then
	echo "ifconfig-loopbacks $version"
	exit 0
fi

a=127
b=200
c=2
d=0
e=23

dryrun=""
nc=""
netmask=255.255.255.255
hexnetmask=0xffffffff
removealias=""
hostprefix=""
listonly=""
HOSTSFILE=/etc/hosts
while [ "$1" != "" ]; do
	if [ "$1" == "-alias" -o "$1" == "--no-alias" -o "$1" == "-d" -o "$1" == "down" ]; then
		removealias=1
		shift
	elif [ "$1" == "--force" -o "$1" == "-f" ]; then
		force=1
		shift
	elif [ "${1:0:12}" == "--interface=" ]; then
		ifname=${1:9}
		shift
	elif [ "$1" == "-i" ]; then
		shift
		if [ "$1" != "" ]; then
			ifname="$1"
			shift
		else
			echo "Missing interface name to \`-i' option." >&2
		fi
	elif [ "$1" == "--dry-run" -o "$1" == "-n" ]; then
		dryrun=1
		shift
	elif [ "${1:0:9}" == "--subnet=" ]; then
		subnet=${1:9}
		OLD_IFS="$IFS"
		IFS="./"
		read a b c d e < <(printf "%s" "$subnet")
		IFS="$OLD_IFS"
		if [ "$e" = "" ]; then e=23; fi
		if [    "$a" -ne "$a" -o "$a" -lt 1 -o "$a" -gt 254 -o \
			"$b" -ne "$b" -o "$b" -lt 0 -o "$b" -gt 254 -o \
			"$c" != $[$c / 2 * 2] -o "$c" -lt 0 -o "$c" -gt 254 -o \
			"$d" != "0" -o \
			"$e" != "23" ]; then
			echo "Invalid subnet \`$subnet'" >&2
			exit 1
		fi
		shift
	elif [ "${1:0:11}" == "--ncsubnet=" ]; then
		subnet=${1:11}
		OLD_IFS="$IFS"
		IFS="./"
		read a b c d e < <(printf "%s" "$subnet")
		if [ "$e" = "" ]; then e=21; fi
		IFS="$OLD_IFS"
		if [    "$a" -ne "$a" -o "$a" -lt 1 -o "$a" -gt 254 -o \
			"$b" -ne 0 -o \
			"$c" -ne "$c" -o "$c" -lt 0 -o "$c" -gt 254 -o \
			"$d" != "1" -o \
			"$e" != "21" ]; then
			echo "Invalid subnet \`$subnet'" >&2
			exit 1
		fi
		nc=1
		shift
	elif [ "${1:0:13}" == "--hostprefix=" ]; then
		hostprefix=${1:13}
		shift
	elif [ "${1:0:11}" == "--hostfile=" ]; then
		HOSTSFILE=${1:11}
		shift
	elif [ "$1" == "--list" -o "$1" == "-l" ]; then
		listonly=1
		shift
	else
		echo "Invalid parameter \`$1'" >&2
		exit 1
	fi
done

if [ \( "$hostprefix" != "" \) -a \( ! -w "$HOSTSFILE" \) ]; then
	echo "The file \`$HOSTSFILE' is not writeable." >&2
	exit 1
fi

progress=""
if [ -t 0 -a -t 1 ]; then
	progress=1
fi

if [ ! "$nc" ]; then
	cstart="$c"
	cend=$[$cstart + 1]
	dstart=2
#	dend=251
	dend=3
	dincr=1
	total=$[($dend - $dstart + 1) * ($cend - $cstart + 1)]
fi

counter=0

progressshown=""

if [ "$nc" == "1" ]; then
	aa=$a; bb=$b; cc=$c; dd=$d
	cstart="$c"
	cend=$[$cstart + 8 - 1]
	dstart="$d"
	dincr=4
	dend=253
	total=$[((($dend - $dstart) / $dincr) + 1) * ($cend - $cstart + 1)]
fi

IFCONFIGA="ifconfig -a"

lastifnumber=-1
lastifnumberpat="#lastifnumber="
if [ "$UNAME" == "Linux" ]; then
	checknextline=no
	possibleif=""
	while read line; do
		if [[ "$line" == "$ifname":* ]]; then
			ifnumber=${line//$ifname:/}
			if [ "$ifnumber" -gt "$lastifnumber" ]; then
				lastifnumber=$ifnumber
			fi
		fi
		if [ "$checknextline" == "yes" ]; then
			checknextline=no
			if [[ $line == "$ifname":* ]]; then
				possibleif=$line
				checknextline=yes
			else
				ifaddr=$line
				echo $ifname $ifnumber $ifaddr
				declare "ifaddr_$ifname_$ifnumber=$ifaddr"
				ifaddr=${ifaddr//./_}
				declare "ifname_$ifaddr=$ifname:$ifnumber"
			fi
		else
			if [[ "$line" == "$ifname":* ]]; then
				possibleif=$line
				checknextline=yes
			else
				possibleif=""
				checknextline=no
			fi
		fi
	done < <(
		$IFCONFIGA | sed -n \
		-e 's/^\('"$ifname"':[0-9][0-9]*\)[^0-9].*$/\1/p' \
		-e "$(printf 's/^[\t ]*inet addr:\([0-9.]*\)[\t ][\t ]*Mask:'"$netmask"'.*$/\\1/p')"
		)
fi
if [ "$UNAME" == "Darwin" ]; then

	while read line; do
		echo $ifaddr $ifname
		declare "ifaddr_$ifaddr=$ifname"
	done < <(
	ifconfig "$ifname" | sed -n "$(printf 's/^[\t ]*inet \([0-9.]*\) netmask '"$hexnetmask"'.*$/\\1/p')" | sort -t. -g -k1,1 -k2,2 -k3,3 -k4,4
	)

fi
#echo "last IF: $ifname:$lastifnumber"
#echo "lo:23976 is: $ifaddr_23976"
#echo "99.99.3.3 is: $ifname_99_99_3_3"

#declare "ens160_56_0_0_1=ens160:0"

ifidx=0
for c in $(seq $cstart $cend); do
	for d in $(seq $dstart $dincr $dend); do
		ifaddr=$a.$b.$c.$d
		ifaddrref=$a_$b_$c_$d
		if [ "$listonly" ]; then
			printf "ens160:%s %s/21\n" "$ifidx" "$ifaddr"
			ifidx=$[$ifidx + 1]
		else
			echo $ifaddr
			ind="${ifname}_$ifaddrref" this_ifaddr="${!ind}"
			echo $ind
			echo $this_ifaddrref
			exit 1
		fi
#		elif [ \( \( "$ifaddr" != "$existingifaddr" \) -o "$force" -o "$removealias" \) -a ! "$listonly" ]; then
#			ifaddr2=$a-$b-$c-$d
#			ifaddrpat=$a\\.$b\\.$c\\.$d
#			thisifname=
#			if [ "$hostprefix" != "" ]; then
#				hostent="$(printf "%s\t%s%s-%s\n" "$ifaddr" "$hostprefix" $[$counter + 1] "$ifaddr2")"
#				hostentprintf="$(printf "%s\\\\t%s%s-%s\\\\n" "$ifaddr" "$hostprefix" $[$counter + 1] "$ifaddr2")"
#				hostpattern="$(printf "/^\\s*%s[[:space:]]+%s-%s\\s*$/" "$ifaddrpat" "$hostprefix" "$ifaddr2")"
#			fi
#			if [ "$removealias" -a "$dryrun" ]; then
#				echo $specificifname $ifname $ifaddr $existingifaddr
#				if [ "$specificifname" != "$ifname" -a "$ifaddr" == "$existingifaddr" ]; then
#					echo ifconfig "$specificifname" down
#				elif [ "$specificifname" == "$ifname" ]; then
#					echo ifconfig "$specificifname" -alias $ifaddr netmask "$netmask"
#				fi
#				if [ "$hostprefix" != "" ]; then
#					echo sed -Ei \"\" \'"$hostpattern"\'d \'"$HOSTSFILE"\'
#				fi
#			elif [ "$removealias" -a ! "$dryrun" ]; then
#				ifconfig "$specificifname" -alias $ifaddr netmask "$netmask" 2>/dev/null
#				if [ "$hostprefix" != "" ]; then
#					sed -Ei "" "$hostpattern"d "$HOSTSFILE" || exit
#				fi
#			fi
#			if [ ! "$removealias" ]; then
#				if [ "$NEXTIF" != "" ]; then
#					nextifname=$ifname:$NEXTIF
#					NEXTIF=$[$NEXTIF + 1]
#				else
#					nextifname="$ifname"
#				fi
#				if [ "$dryrun" ]; then
#					if [ "$ifname" != "$nextifname" ]; then
#						echo ifconfig "$nextifname" $ifaddr netmask "$netmask"
#					else
#						echo ifconfig "$nextifname" alias $ifaddr netmask "$netmask"
#					fi
#					if [ "$hostprefix" != "" ]; then
#						echo printf \'"$hostentprintf"\' \>\> \'"$HOSTSFILE"\'
#					fi
#				else
#					ifconfig "$nextifname" alias $ifaddr netmask "$netmask"
#					rc=$?
#					if [ $rc -gt 0 ]; then
#						echo Cannot alias $specificifname $ifaddr\; are you root\?
#						exit $rc
#					fi
#					if [ "$hostprefix" != "" ]; then
#						printf "%s" "$hostent" >> "$HOSTSFILE" || exit
#					fi
#				fi
#			fi
#			if [ "$progress" -a ! "$dryrun" ]; then
#				progressshown=1
#				echo -n -e "\r$[100 * $counter / $total]% ... "
#			fi
#			counter=$[$counter + 1]
#		fi
	done
done

if [ "$progress" -a "$progressshown" ]; then
	echo -e "\r100% completed"
fi
